### PR TITLE
Updates To Just About Every Page

### PR DESCRIPTION
**Pull request by ElementalCrisis**
Updated Downloads and Setup page with new information and fixed any incorrect links. Updated documentation outline adding placeholder pages for future updates. Added a page called Making Changes that tells people how they can help out. Also the wiki_ pages are no longer in use as all relevant information has been moved over to the it's corresponding documentation page.

### CODE REVIEW

**Comment by CuddleBear92** [comment]
after the new changes Google Chrome warns for errors



not sure if its still an issue, but it still shows up. 

if its still safe then it needs to be added to Google Web Tools: http://www.google.com/webmasters/tools/

**Comment by ElementalCrisis** [comment]
That's intresting, just tried on Chrome mobile and I didn't get that warning. What does it say when you click details?

**Comment by CuddleBear92** [comment]
it basically give you a link to here: https://www.google.com/safebrowsing/diagnostic?site=http%3A%2F%2Fjapanesemediamanager.github.io%2F&client=googlechrome&hl=en-US

**Comment by ElementalCrisis** [comment]
I'll take a look at the changes I made when I'm at my computer.

**Comment by ElementalCrisis** [comment]
Went through the changes, not seeing what could be causing it. 

I've asked lwerndly to check the WebMaster Tools to get some more information. I've also noticed that Google has flagged http://www.jmediamanager.org/ though no idea why. At the moment my best guess is the Anime Buddy link. In addition to taking you to the site to download it, it opens the Windows Store App on your computer as well. Maybe that's what's considered the unwanted malicious software that's supposedly being installed. 

EDIT: 
I'm no longer getting the warning message, do you still see it?

**Comment by CuddleBear92** [comment]
yeah still getting the error, also get the same error on the other site.
note that if you enter the site and just reload the page it will not show the error again, you have to enter the url again on a new tab or click your way to the site with a link

**Comment by ElementalCrisis** [comment]
Interesting, just tried in Firefox, Edge and Chrome and for me I don't get the warnings anymore. Regardless once I hear back from lwerndly I can make the changes to fix this false positive.

**Comment by CuddleBear92** [comment]
well the warning is a Chrome thing, the others would not have the same message, they might not even test the sites the same ways.

**Comment by t0815** [comment]
hi, just for info. Now you get the warning in FireFox too.... Some idiot must have reported the github -pages as harmfull..... -_-

**Comment by CuddleBear92** [comment]
either that or this changes triggered something. as these warnings started right after this pull was added

**Comment by ElementalCrisis** [comment]
It's a false positive, that's for sure. 

https://www.virustotal.com/cs/url/b56a15d271c50c06a7157b299f655bac4117629483e7a633f415af0c56f3431e/analysis/1441046846/

**Comment by CuddleBear92** [comment]
yup, but the warning is still there, an annoyance aswell as pushing new people away from the site.
im not saying its infected, just that it started right when the new changes on this issue was made.

**Comment by ElementalCrisis** [comment]
Oh yeah I was posting that just in case anyone had doubts, we just need to hear back from lwerndly and this will be sorted out.

**Comment by speedello** [comment]
I have submitted a request to Google to have it reviewed

**Comment by xsystematic** [comment]
I'm guessing it's from the x86 hasher.dll on 3.4.3.2. Had Kaspersky warn me a few weeks ago but I just ignored it.

https://www.virustotal.com/en/file/a8d0fddd238faaa11043189db4cc2f7bc8ab54e57a994a4ba64d2e83c28a51ee/analysis/1441152941/

Edit: On 3.4.4.1 now and no warnings about the hasher.dll

**Pull request merged**
